version: '3.8'

services:
    nginx:
        container_name: nginx
        depends_on:
            - wordpress
        build: ./requirements/nginx
        restart: on-failure
        ports:
            - "443:443"
        networks:
            - inception
        env_file:
            - .env
    
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        restart: unless-stopped
        expose:
            - "3306"
        networks:
            - inception
        env_file:
            - .env

    wordpress:
        container_name: wordpress
        depends_on:
            - mariadb
        build: ./requirements/wordpress
        expose:
            - "9000"
        networks:
            - inception
        env_file:
            - .env
networks:
    inception:
        driver: bridge
