version: '3.8'

services:
    nginx:
        container_name: nginx
        depends_on:
            - wordpress
        build: ./requirements/nginx
        restart: on-failure
        ports:
            - "443:443"
        networks:
            - inception
        env_file:
            - .env
        volumes:
            - v_wordpress:/var/www/html

    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        restart: unless-stopped
        expose:
            - "3306"
        networks:
            - inception
        env_file:
            - .env
        volumes:
            - v_mariadb:/var/lib/mysql

    wordpress:
        container_name: wordpress
        depends_on:
            - mariadb
        build: ./requirements/wordpress
        expose:
            - "9000"
        networks:
            - inception
        env_file:
            - .env
        volumes:
            - v_wordpress:/var/www/html
networks:
    inception:
        driver: bridge

volumes:
    v_wordpress:
        name : v_wordpress
        driver: local
        driver_opts:
            type: 'none'
            o: bind
            device: Users/zmrabet/data/wordpress
    v_mariadb:
        name: v_mariadb
        driver: local
        driver_opts:
            type: 'none'
            o: bind
            device: Users/zmrabet/data/mariadb