version: '3.8'

services:
    nginx:
        container_name: nginx
        depends_on:
            - wordpress
        build: ./requirements/nginx
        restart: unless-stopped
        ports:
            - "443:443"
        networks:
            - inception
        env_file:
            - .env
        volumes:
            - v_wordpress:/var/www/html

    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        restart: unless-stopped
        expose:
            - "3306"
        networks:
            - inception
        env_file:
            - .env
        volumes:
            - v_mariadb:/var/lib/mysql

    wordpress:
        container_name: wordpress
        depends_on:
            - mariadb
        build: ./requirements/wordpress
        restart: unless-stopped
        expose:
            - "9000"
        networks:
            - inception
        env_file:
            - .env
        volumes:
            - v_wordpress:/var/www/html
    adminer:
        container_name: adminer
        build: ./requirements/bonus/adminer
        restart: unless-stopped
        ports:
            - "600:80"
        networks:
            - inception
        env_file:
            - .env

    redis:
        container_name: redis
        depends_on:
            - wordpress
        build: ./requirements/bonus/redis
        networks:
            - inception
        env_file:
            - .env
        volumes:
            - v_wordpress:/var/www/html
    
    website:
        container_name: website
        build: ./requirements/bonus/website
        restart: unless-stopped
        ports:
            - "3000:3000"
        networks:
            - inception
        env_file:
            - .env

    cadvisor:
        container_name: cadvisor
        build: ./requirements/bonus/cadvisor
        restart: unless-stopped
        ports:
            - "8080:8080"
        networks:
            - inception
        env_file:
            - .env
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/:/rootfs"
            - "/var/run:/var/run"
            - "/sys:/sys"
            - "/var/lib/docker/:/var/lib/docker"
            - "/dev/disk/:/dev/disk"

networks:
    inception:
        driver: bridge

volumes:
    v_wordpress:
        name : v_wordpress
        driver: local
        driver_opts:
            type: 'none'
            o: bind
            device: /home/zmrabet/data/wordpress
    v_mariadb:
        name: v_mariadb
        driver: local
        driver_opts:
            type: 'none'
            o: bind
            device: /home/zmrabet/data/mariadb