version: '3.8'

services:
    nginx:
        container_name: nginx
        image: nginx
        depends_on:
            - wordpress
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        restart: on-failure
        ports:
            - "443:443"
        networks:
            - inception
        env_file:
            - .env
        volumes:
            - v_wordpress:/var/www/html

    mariadb:
        container_name: mariadb
        image: mariadb
        build: 
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        restart: on-failure
        expose:
            - "3306"
        networks:
            - inception
        env_file:
            - .env
        volumes:
            - v_mariadb:/var/lib/mysql

    wordpress:
        container_name: wordpress
        image: wordpress
        depends_on:
            - mariadb
        build: 
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        restart: on-failure
        expose:
            - "9000"
        networks:
            - inception
        env_file:
            - .env
        volumes:
            - v_wordpress:/var/www/html

    adminer:
        container_name: adminer
        image: adminer
        build: 
            context: ./requirements/bonus/adminer
            dockerfile: Dockerfile
        depends_on:
            - mariadb
        restart: on-failure
        ports:
            - "600:80"
        networks:
            - inception
        env_file:
            - .env

    redis:
        container_name: redis
        image: redis
        build: 
            context: ./requirements/bonus/redis
            dockerfile: Dockerfile
        depends_on:
            - wordpress
        restart: on-failure
        networks:
            - inception
        env_file:
            - .env
        volumes:
            - v_wordpress:/var/www/html
    
    website:
        container_name: website
        image: website
        build: 
            context: ./requirements/bonus/website
            dockerfile: Dockerfile
        restart: on-failure
        ports:
            - "3000:3000"
        networks:
            - inception
        env_file:
            - .env
    
    portainer:
        container_name: portainer
        image: portainer
        build: 
            context: ./requirements/bonus/portainer
            dockerfile: Dockerfile
        restart: on-failure
        ports:
            - "9000:9000"
        networks:
            - inception
        volumes:
            - v_portainer:/data
            - /var/run/docker.sock:/var/run/docker.sock

networks:
    inception:
        name: inception
        driver: bridge

volumes:
    v_wordpress:
        name : v_wordpress
        driver: local
        driver_opts:
            type: 'none'
            o: bind
            device: /Users/apollo/data/wordpress

    v_mariadb:
        name: v_mariadb
        driver: local
        driver_opts:
            type: 'none'
            o: bind
            device: /Users/apollo/data/mariadb

    v_portainer:
        name: v_portainer
        driver: local
        driver_opts:
            o: bind
            type: 'none'
            device: /Users/apollo/data/portainer
